# conf/base/parameters.yml
# Shared parameters across all pipelines

data:
  pairs:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - BNBUSDT
    - XRPUSDT
  date_range:
    start:
      year: 2025
      month: 11
      day: 1
    end:
      year: 2025
      month: 12
      day: 31
  storage_path: "data/01_raw/market.duckdb"

