# conf/base/parameters.yml

data:
  store:
    type: duckdb/spot
    params:
      db_path: "data/01_raw/market.duckdb"
  
  loader:
    type: binance/spot      

  pairs:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    - BNBUSDT
    - XRPUSDT
  period:
    start:
      year: 2025
      month: 12
      day: 1
    end:
      year: 2025
      month: 12
      day: 31

